#!/usr/bin/env bash
#
# pack.sh — build distributables of the wizard into dist/:
#
#   dist/monorepo-wizard.tar.gz   init-project.sh + next-steps.sh + templates/
#   dist/monorepo-wizard.sh       single self-contained executable: the same
#                                 payload embedded as base64, self-extracted
#                                 to a temp dir at runtime
#
# The single file dispatches on its first argument:
#   ./monorepo-wizard.sh [init] [wizard options...]     scaffold (default)
#   ./monorepo-wizard.sh next-steps [options...]        status summary
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

for f in init-project.sh next-steps.sh templates; do
  [ -e "$f" ] || { printf 'error: %s not found next to pack.sh\n' "$f" >&2; exit 1; }
done

mkdir -p dist

tar czf dist/monorepo-wizard.tar.gz init-project.sh next-steps.sh templates

{
  cat <<'STUB'
#!/usr/bin/env bash
# monorepo-wizard.sh — self-contained bundle of init-project.sh,
# next-steps.sh and templates/. Generated by pack.sh; do not edit — edit
# the sources and re-pack.
#
#   ./monorepo-wizard.sh [init] [wizard options...]     scaffold (default)
#   ./monorepo-wizard.sh next-steps [options...]        status summary
set -euo pipefail

tmp=$(mktemp -d "${TMPDIR:-/tmp}/monorepo-wizard.XXXXXX")
trap 'rm -rf "$tmp"' EXIT

awk 'found { print } /^__PAYLOAD_BELOW__$/ { found=1 }' "$0" \
  | base64 -d | tar xz -C "$tmp"

cmd="init"
case "${1:-}" in
  init|next-steps) cmd=$1; shift ;;
esac

if [ "$cmd" = "next-steps" ]; then
  bash "$tmp/next-steps.sh" "$@"
else
  bash "$tmp/init-project.sh" "$@"
fi
# Nothing may execute past this line: the payload follows.
exit $?
STUB
  printf '__PAYLOAD_BELOW__\n'
  base64 < dist/monorepo-wizard.tar.gz
} > dist/monorepo-wizard.sh
chmod +x dist/monorepo-wizard.sh

printf 'packed:\n'
ls -lh dist/monorepo-wizard.tar.gz dist/monorepo-wizard.sh | awk '{ print "  " $5 "\t" $NF }'
