FROM mcr.microsoft.com/dotnet/sdk:{{DOTNET_TAG}} AS build
WORKDIR /src
COPY . .
RUN dotnet restore "src/{{NS}}.Api/{{NS}}.Api.csproj"
RUN dotnet publish "src/{{NS}}.Api/{{NS}}.Api.csproj" -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:{{DOTNET_TAG}} AS final
WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=8080
EXPOSE 8080
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "{{NS}}.Api.dll"]
